eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/test?useSSL=false
  driver-class-name=com.mysql.cj.jdbc.Driver
  username: root
  password: root
 jpa:
  show-sql: true
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
  hibernate:
   ddl-auto: update